# Generated by Django 5.2 on 2025-04-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fornecedor",
            old_name="contato",
            new_name="contacto",
        ),
    ]
