# Generated by Django 5.2 on 2025-04-22 22:59

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0002_rename_contato_fornecedor_contacto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fornecedor",
            name="contacto",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+244000000000", max_length=128, region="AO"
            ),
            preserve_default=False,
        ),
    ]
